const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ENV_PATH = path.join(__dirname, '.env');
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

(async () => {
    console.log('\n=== Lead Generator Setup ===\n');

    let envContent = '';
    if (fs.existsSync(ENV_PATH)) {
        envContent = fs.readFileSync(ENV_PATH, 'utf8');
        if (envContent.includes('AUTH_PASSWORD_HASH=') && !envContent.match(/AUTH_PASSWORD_HASH=\s*$/m)) {
            console.log('Auth already configured in .env. Delete AUTH_PASSWORD_HASH line to reconfigure.');
            rl.close();
            return;
        }
    }

    const username = await ask('Username (default: admin): ') || 'admin';
    const password = await ask('Password: ');
    if (!password || password.length < 6) {
        console.log('Password must be at least 6 characters.');
        rl.close();
        return;
    }

    const hash = await bcrypt.hash(password, 12);
    const secret = crypto.randomBytes(32).toString('hex');

    const lines = [
        '',
        '# Auth (generated by setup.js)',
        `AUTH_USERNAME=${username}`,
        `AUTH_PASSWORD_HASH=${hash}`,
        `JWT_SECRET=${secret}`,
    ];

    fs.appendFileSync(ENV_PATH, lines.join('\n') + '\n');
    console.log(`\nAuth configured for user "${username}".`);
    console.log('JWT secret generated and saved to .env');
    rl.close();
})();
